openapi: 3.0.0
info:
  version: 1.0.0
  title: Pix com QRCode
  description: Pix com QRCode é gerado através dos métodos das mensagens Pac.008
  contact:
    email: desenvolvimento@gokeitecnologia.com
paths: 
  /V1/PIX/QRCodeEstatico:
    parameters:
        - name: token
          in: header
          description: Token JWT
          required: true
          schema:
            type: array
            items:
              type: string
              format: string
          style: simple
          example: >- 
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5bGFuQGJvc2Nhcmluby5jb20iLCJwYXNzd29yZCI6InlhMGdzcWh5NHd6dnV2YjQifQ.yN_8-Mge9mFgsnYHnPEh_ZzNP7YKvSbQ3Alug9HMCsM
    post:
      summary: Liquidação pix via QRcode Estatico.
      tags: 
      - QrCode
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/request_body_qrcode_estatico'
      responses:
        202:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_201_decodifica_qrcode'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_400_bad_request'
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_503'
  /V1/PIX/QRCodeDinamico:
    parameters:
        - name: token
          in: header
          description: Token JWT
          required: true
          schema:
            type: array
            items:
              type: string
              format: string
          style: simple
          example: >- 
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5bGFuQGJvc2Nhcmluby5jb20iLCJwYXNzd29yZCI6InlhMGdzcWh5NHd6dnV2YjQifQ.yN_8-Mge9mFgsnYHnPEh_ZzNP7YKvSbQ3Alug9HMCsM
    post:
      summary: Liquidação pix via QRcode dinâmico.
      tags: 
      - QrCode
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/request_body_qrcode_dinamico'
      responses:
        202:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_201_decodifica_qrcode'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_400_bad_request'
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_503'
  /V1/PIX/decodificaQRCode:
    parameters:
        - name: token
          in: header
          description: Token JWT
          required: true
          schema:
            type: array
            items:
              type: string
              format: string
          style: simple
          example: >- 
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5bGFuQGJvc2Nhcmluby5jb20iLCJwYXNzd29yZCI6InlhMGdzcWh5NHd6dnV2YjQifQ.yN_8-Mge9mFgsnYHnPEh_ZzNP7YKvSbQ3Alug9HMCsM
    post:
      summary: Decodificar Qrcode.
      tags: 
      - QrCode
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/request_body_decodifica_qrcode'
      responses:
        202:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_201_decodifica_qrcode'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_400_bad_request'
        503:
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response_503'



components:
  schemas:
    body_response_201_decodifica_qrcode:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 202
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Accepted
        date:
          type: string
          description: Data.
          example: "2021-07-14 12:41:10"
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        response:
          example: Operação realizada com sucesso.
              
    body_response_400_entry_invalid:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 400
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Entry is invalid.
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        error:
          properties:
            message: 
              example: A entrada contém campos inválidos
    body_response_400_bad_request:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 400
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Bad request.
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        error:
          properties:
            message: 
              example: A entrada contém campos inválidos
    body_response_403:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 403
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Acesso negado.
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        error:
          properties:
            message: 
              example: O Participante não está permitido a acessar esse recurso. 
    body_response_429:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 403
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Too Many Requests
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
    body_response_404:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 403
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Not found.
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        error:
          properties:
            message: 
              example: A entrada associada à chave fornecida não existe
    body_response_503:
      type: object
      properties:
        http_status_code:
          type: string
          description: Código HTTP do erro.
          example: 503
        http_status_message:
          type: string
          description: Status de mensagem.
          example: Service Unavailable.
        date:
          type: string
          description: Data.
          example: '2021-07-14 12:41:10'
        total_execution_time:
          type: number
          description: Tempo total de execução.
          example: 6.5479278564453125
        error:
          properties:
            message: 
              example: O serviço está em manutenção programada
              
    request_body_qrcode_estatico:
      type: object
      required:
      - pagador
      - recebedor
      - chavePix
      - mensagemPix
      properties:
        pagador:
          type: object
          required:
          - valor
          - nomePagador
          - cpfCnpjPagador
          - contaTransacionalPagador
          - agenciaPagador
          properties:
            valor:
              type: number
              minimum: 0
              maximum: 18
            nomePagador:
              type: string
              minimum: 1
              maximum: 140
            cpfCnpjPagador:
              type: integer
              minimum: 0
              maximum: 14
              example: 12822222215
            contaTransacionalPagador:
              type: integer
              minimum: 1
              maximum: 20
              example: 1111108
            agenciaPagador:
              type: integer
              minimum: 1
              maximum: 4
              example: 0001
        recebedor:
          type: object
          required:
          - ispbParticipanteRecebedor
          - cpfCnpjPagador
          - contaTransacionalRecebedor
          - agenciaRecebedor
          properties:
            ispbParticipanteRecebedor:
              type: integer
              minimum: 8
              maximum: 8 
              example: 22222222
            cpfCnpjPagador:
              type: integer
              minimum: 0
              maximum: 14
              example: 45454545455
            contaTransacionalRecebedor:
              type: integer
              minimum: 1
              maximum: 20
              example: 23683707994215
            agenciaRecebedor:
              type: integer
              minimum: 1
              maximum: 4
              example: 5770
        chavePix:
          type: string
          minimum: 0
          maximum: 77
          example: bc@bc.com.br
        mensagemPix:
          type: string
          minimum: 0
          maximum: 140
          example: Campo livre.
    request_body_qrcode_dinamico:
      type: object
      required:
      - pagador
      - recebedor
      - chavePix
      - mensagemPix
      properties:
        pagador:
          type: object
          required:
          - valor
          - nomePagador
          - cpfCnpjPagador
          - contaTransacionalPagador
          - agenciaPagador
          properties:
            valor:
              type: number
              minimum: 0
              maximum: 18
            nomePagador:
              type: string
              minimum: 1
              maximum: 140
            cpfCnpjPagador:
              type: integer
              minimum: 0
              maximum: 14
              example: 12822222215
            contaTransacionalPagador:
              type: integer
              minimum: 1
              maximum: 20
              example: 1111108
            agenciaPagador:
              type: integer
              minimum: 1
              maximum: 4
              example: 0001
        recebedor:
          type: object
          required:
          - ispbParticipanteRecebedor
          - cpfCnpjPagador
          - contaTransacionalRecebedor
          - agenciaRecebedor
          properties:
            ispbParticipanteRecebedor:
              type: integer
              minimum: 8
              maximum: 8 
              example: 22222222
            cpfCnpjPagador:
              type: integer
              minimum: 0
              maximum: 14
              example: 45454545455
            contaTransacionalRecebedor:
              type: integer
              minimum: 1
              maximum: 20
              example: 23683707994215
            agenciaRecebedor:
              type: integer
              minimum: 1
              maximum: 4
              example: 5770
        chavePix:
          type: string
          minimum: 0
          maximum: 77
          example: bc@bc.com.br
        mensagemPix:
          type: string
          minimum: 0
          maximum: 140
          example: Campo livre.
    request_body_decodifica_qrcode:
      type: object
      required:
      - payload
      properties:
        payload:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5bGFuQGJvc2Nhcmluby5jb20iLCJwYXNzd29yZCI6InlhMGdzcWh5NHd6dnV2YjQifQ.yN_8-Mge9mFgsnYHnPEh_ZzNP7YKvSbQ3Alug9HMCsM